import type { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'foods',
    name: 'Foods & Drinks',
    words: [
      'coffee',
      'tea',
      'juice',
      'soda',
      'lemonade',
      'smoothie',
      'milk',
      'burger',
      'pizza',
      'pasta',
      'sushi',
      'taco',
      'burrito',
      'salad',
      'soup',
      'sandwich',
      'steak',
      'sausage',
      'bacon',
      'omelet',
      'pancake',
      'waffle',
      'toast',
      'bagel',
      'croissant',
      'donut',
      'cookie',
      'cake',
      'pie',
      'ice cream',
      'chocolate',
      'cheese',
      'yogurt',
      'apple',
      'banana',
      'grape',
      'orange',
      'lemon',
      'strawberry',
      'watermelon',
      'carrot',
      'potato',
      'tomato',
      'mushroom',
      'rice',
      'noodle',
      'popcorn',
      'pretzel',
      'curry',
      'dumpling',
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    words: [
      'lion',
      'tiger',
      'elephant',
      'giraffe',
      'zebra',
      'panda',
      'bear',
      'wolf',
      'fox',
      'rabbit',
      'deer',
      'horse',
      'cow',
      'pig',
      'goat',
      'sheep',
      'dog',
      'cat',
      'mouse',
      'hamster',
      'camel',
      'otter',
      'beaver',
      'kangaroo',
      'monkey',
      'gorilla',
      'chimpanzee',
      'sloth',
      'koala',
      'eagle',
      'owl',
      'parrot',
      'penguin',
      'flamingo',
      'peacock',
      'duck',
      'swan',
      'shark',
      'whale',
      'dolphin',
      'octopus',
      'crab',
      'lobster',
      'seal',
      'turtle',
      'crocodile',
      'snake',
      'frog',
      'lizard',
      'bat',
    ],
  },
  {
    id: 'countries',
    name: 'Countries',
    words: [
      'canada',
      'united states',
      'mexico',
      'brazil',
      'argentina',
      'chile',
      'peru',
      'colombia',
      'france',
      'spain',
      'portugal',
      'italy',
      'germany',
      'netherlands',
      'belgium',
      'switzerland',
      'norway',
      'sweden',
      'finland',
      'denmark',
      'poland',
      'ukraine',
      'greece',
      'turkey',
      'hungary',
      'egypt',
      'morocco',
      'kenya',
      'nigeria',
      'jamaica',
      'ethiopia',
      'india',
      'china',
      'japan',
      'south korea',
      'thailand',
      'vietnam',
      'philippines',
      'indonesia',
      'malaysia',
      'singapore',
      'australia',
      'new zealand',
      'ghana',
      'romania',
      'cuba',
      'pakistan',
      'nepal',
      'ireland',
      'iceland',
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    words: [
      'teacher',
      'doctor',
      'nurse',
      'dentist',
      'pilot',
      'driver',
      'chef',
      'baker',
      'farmer',
      'lawyer',
      'judge',
      'actor',
      'singer',
      'dancer',
      'painter',
      'writer',
      'designer',
      'engineer',
      'architect',
      'plumber',
      'electrician',
      'mechanic',
      'firefighter',
      'police officer',
      'soldier',
      'scientist',
      'librarian',
      'cashier',
      'waiter',
      'barber',
      'tailor',
      'photographer',
      'reporter',
      'editor',
      'programmer',
      'coach',
      'athlete',
      'fisherman',
      'builder',
      'carpenter',
      'receptionist',
      'manager',
      'janitor',
      'lifeguard',
      'paramedic',
      'therapist',
      'veterinarian',
      'florist',
      'mail carrier',
      'musician',
    ],
  },
];

export function getThemeById(themeId: Theme['id']) {
  return THEMES.find((theme) => theme.id === themeId) ?? null;
}
